#!/bin/bash

function download() {
    url=$1
    dest=$2

    response=$(curl -X GET ${url} -o -)
    format=$(echo ${response} | jq -r .format)
    if [ "${format}" = "base64" ] ; then
        echo ${response} | jq -j .content | base64 -d > $dest
    elif [ "${format}" = "text" ] ; then
        echo ${response} | jq -j .content > $dest
    else
        echo "Format ${format} of file ${dest} not supported"
        echo ${response} | jq -j .content > $dest
    fi
}

notebook_created="no"

function get_notebook() {
    ## Creates a new notebook if needed. Sets flag to delete if
    ## notebook was re-created.
    apiurl=$1
    sessionid=$2
    serviceid=$3
    svcinfo=`curl --silent -X GET "${apiurl}/${serviceid}" -H  "accept: application/json"`
    if [ $(echo ${svcinfo} | jq -j .sessionId) = "${sessionid}" ] ; then
        return ## NOTEBOOK_URL unchanged.
    fi
    
    svcinfo=`curl --silent -X POST "${apiurl}" -H  "accept: application/json" \
                  -H  "Content-Type: application/json" -d "{\"sessionId\":\"${sessionid}\"}"`
    notebook_created="yes"
    
    svcurl=`echo ${svcinfo} | jq -j .serviceURL`
    if [ "${svcurl}" = "null" ] ; then
        echo "Session ${sessionid} no longer exists. Cannot download data."
        exit 1
    fi

    SERVICE_ID=`echo ${svcinfo} | jq -j .id`
    echo "Wait for service ${SERVICE_ID} to be re-created at ${svcurl}."
    while ! curl --silent -IL -X GET ${svcurl} | grep "200 OK" ; do
        sleep 5
    done
    NOTEBOOK_URL=${svcurl}
}

function delete_notebook() {
    apiurl=$1
    if [ "${notebook_created}" = "yes" ] ; then
        curl -X DELETE "${apiurl}/${SERVICE_ID}" -H  "accept: */*"
    fi
}

function download_working_dir_data() {
    if [ ! -e download_filelist.dat ] ; then
        echo "Nothing to download from working dir."
        return
    fi
    apiurl=$1
    for file in `cat download_filelist.dat` ; do
        download ${apiurl}/${file} ${HOME}/${file}
    done
}

conda install -y -c conda-forge curl jq || exit 1


# =======================================================
# Everything below here is generated by the snapshot job:
# =======================================================
NOTEBOOK_URL=https://swirrl.climate4impact.eu/swirrl/jupyter/e2965376-f8ec-4f19-b4d4-40f083f4427e
SERVICE_ID=e2965376-f8ec-4f19-b4d4-40f083f4427e
get_notebook http://swirrl-api/swirrl-api/v1.0/notebook 0f8a193f-345f-4633-bef9-159b46176d3e e2965376-f8ec-4f19-b4d4-40f083f4427e
mkdir -p ~/data/staginghistory/stage.00010
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00010/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00010/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00010/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20150101-20341231.nc ~/data/staginghistory/stage.00010/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20150101-20341231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00010/tasmax_day_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_20150101-20191231.nc ~/data/staginghistory/stage.00010/tasmax_day_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_20150101-20191231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00010/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_avg-t.nc ~/data/staginghistory/stage.00010/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_avg-t.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00010/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20350101-20541231.nc ~/data/staginghistory/stage.00010/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20350101-20541231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00010/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc ~/data/staginghistory/stage.00010/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00010/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc ~/data/staginghistory/stage.00010/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00010/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc ~/data/staginghistory/stage.00010/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00010/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00010/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00010/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00010/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00010/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20950101-21001231.nc ~/data/staginghistory/stage.00010/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20950101-21001231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00010/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc ~/data/staginghistory/stage.00010/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00010/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc ~/data/staginghistory/stage.00010/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00010/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20550101-20741231.nc ~/data/staginghistory/stage.00010/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20550101-20741231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00010/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc ~/data/staginghistory/stage.00010/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00010/swirrl_fileinfo.json ~/data/staginghistory/stage.00010/swirrl_fileinfo.json
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00010/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20750101-20941231.nc ~/data/staginghistory/stage.00010/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20750101-20941231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00010/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20240101-20241231.nc ~/data/staginghistory/stage.00010/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20240101-20241231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00010/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc ~/data/staginghistory/stage.00010/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc
mkdir -p ~/data/staginghistory/stage.00009
ln ~/data/staginghistory/stage.00010//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
ln ~/data/staginghistory/stage.00010//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20150101-20341231.nc ~/data/staginghistory/stage.00009/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20150101-20341231.nc
ln ~/data/staginghistory/stage.00010//tasmax_day_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_20150101-20191231.nc ~/data/staginghistory/stage.00009/tasmax_day_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_20150101-20191231.nc
ln ~/data/staginghistory/stage.00010//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20350101-20541231.nc ~/data/staginghistory/stage.00009/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20350101-20541231.nc
ln ~/data/staginghistory/stage.00010//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc ~/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc
ln ~/data/staginghistory/stage.00010//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc ~/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc
ln ~/data/staginghistory/stage.00010//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc ~/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc
ln ~/data/staginghistory/stage.00010//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00010//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
ln ~/data/staginghistory/stage.00010//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20950101-21001231.nc ~/data/staginghistory/stage.00009/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20950101-21001231.nc
ln ~/data/staginghistory/stage.00010//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc ~/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc
ln ~/data/staginghistory/stage.00010//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc ~/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc
ln ~/data/staginghistory/stage.00010//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20550101-20741231.nc ~/data/staginghistory/stage.00009/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20550101-20741231.nc
ln ~/data/staginghistory/stage.00010//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc ~/data/staginghistory/stage.00009/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00009/swirrl_fileinfo.json ~/data/staginghistory/stage.00009/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00010//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20750101-20941231.nc ~/data/staginghistory/stage.00009/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20750101-20941231.nc
ln ~/data/staginghistory/stage.00010//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20240101-20241231.nc ~/data/staginghistory/stage.00009/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20240101-20241231.nc
ln ~/data/staginghistory/stage.00010//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc ~/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc
mkdir -p ~/data/staginghistory/stage.00008
ln ~/data/staginghistory/stage.00009//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00008/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20150101-20341231.nc ~/data/staginghistory/stage.00008/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20150101-20341231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_20150101-20191231.nc ~/data/staginghistory/stage.00008/tasmax_day_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_20150101-20191231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20350101-20541231.nc ~/data/staginghistory/stage.00008/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20350101-20541231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc ~/data/staginghistory/stage.00008/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc ~/data/staginghistory/stage.00008/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc ~/data/staginghistory/stage.00008/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00008/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00008/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20950101-21001231.nc ~/data/staginghistory/stage.00008/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20950101-21001231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc ~/data/staginghistory/stage.00008/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc ~/data/staginghistory/stage.00008/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20550101-20741231.nc ~/data/staginghistory/stage.00008/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20550101-20741231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00008/swirrl_fileinfo.json ~/data/staginghistory/stage.00008/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00009//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20750101-20941231.nc ~/data/staginghistory/stage.00008/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20750101-20941231.nc
ln ~/data/staginghistory/stage.00009//tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20240101-20241231.nc ~/data/staginghistory/stage.00008/tas_day_EC-Earth3_ssp585_r1i1p1f1_gr_20240101-20241231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc ~/data/staginghistory/stage.00008/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc
mkdir -p ~/data/staginghistory/stage.00007
ln ~/data/staginghistory/stage.00008//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00007/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20150101-20341231.nc ~/data/staginghistory/stage.00007/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20150101-20341231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_20150101-20191231.nc ~/data/staginghistory/stage.00007/tasmax_day_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_20150101-20191231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20350101-20541231.nc ~/data/staginghistory/stage.00007/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20350101-20541231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc ~/data/staginghistory/stage.00007/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc ~/data/staginghistory/stage.00007/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc ~/data/staginghistory/stage.00007/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00007/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00007/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20950101-21001231.nc ~/data/staginghistory/stage.00007/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20950101-21001231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc ~/data/staginghistory/stage.00007/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc ~/data/staginghistory/stage.00007/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20550101-20741231.nc ~/data/staginghistory/stage.00007/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20550101-20741231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00007/swirrl_fileinfo.json ~/data/staginghistory/stage.00007/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00008//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20750101-20941231.nc ~/data/staginghistory/stage.00007/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20750101-20941231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc ~/data/staginghistory/stage.00007/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc
mkdir -p ~/data/staginghistory/stage.00006
ln ~/data/staginghistory/stage.00007//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00006/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20150101-20341231.nc ~/data/staginghistory/stage.00006/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20150101-20341231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_20150101-20191231.nc ~/data/staginghistory/stage.00006/tasmax_day_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_20150101-20191231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20350101-20541231.nc ~/data/staginghistory/stage.00006/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20350101-20541231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc ~/data/staginghistory/stage.00006/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc ~/data/staginghistory/stage.00006/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc ~/data/staginghistory/stage.00006/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00006/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00006/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20950101-21001231.nc ~/data/staginghistory/stage.00006/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20950101-21001231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc ~/data/staginghistory/stage.00006/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc ~/data/staginghistory/stage.00006/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20550101-20741231.nc ~/data/staginghistory/stage.00006/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20550101-20741231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00006/swirrl_fileinfo.json ~/data/staginghistory/stage.00006/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00007//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20750101-20941231.nc ~/data/staginghistory/stage.00006/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20750101-20941231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc ~/data/staginghistory/stage.00006/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc
mkdir -p ~/data/staginghistory/stage.00005
ln ~/data/staginghistory/stage.00006//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00005/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20150101-20341231.nc ~/data/staginghistory/stage.00005/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20150101-20341231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_20150101-20191231.nc ~/data/staginghistory/stage.00005/tasmax_day_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_20150101-20191231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20350101-20541231.nc ~/data/staginghistory/stage.00005/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20350101-20541231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc ~/data/staginghistory/stage.00005/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc ~/data/staginghistory/stage.00005/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc ~/data/staginghistory/stage.00005/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00005/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00005/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20950101-21001231.nc ~/data/staginghistory/stage.00005/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20950101-21001231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc ~/data/staginghistory/stage.00005/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc ~/data/staginghistory/stage.00005/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20550101-20741231.nc ~/data/staginghistory/stage.00005/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20550101-20741231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00005/swirrl_fileinfo.json ~/data/staginghistory/stage.00005/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00006//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20750101-20941231.nc ~/data/staginghistory/stage.00005/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20750101-20941231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc ~/data/staginghistory/stage.00005/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc
mkdir -p ~/data/staginghistory/stage.00004
ln ~/data/staginghistory/stage.00005//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00004/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20150101-20341231.nc ~/data/staginghistory/stage.00004/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20150101-20341231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_20150101-20191231.nc ~/data/staginghistory/stage.00004/tasmax_day_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_20150101-20191231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20350101-20541231.nc ~/data/staginghistory/stage.00004/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20350101-20541231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc ~/data/staginghistory/stage.00004/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc ~/data/staginghistory/stage.00004/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc ~/data/staginghistory/stage.00004/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00004/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00004/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20950101-21001231.nc ~/data/staginghistory/stage.00004/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20950101-21001231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc ~/data/staginghistory/stage.00004/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc ~/data/staginghistory/stage.00004/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20550101-20741231.nc ~/data/staginghistory/stage.00004/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20550101-20741231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00004/swirrl_fileinfo.json ~/data/staginghistory/stage.00004/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00005//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20750101-20941231.nc ~/data/staginghistory/stage.00004/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20750101-20941231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc ~/data/staginghistory/stage.00004/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc
mkdir -p ~/data/staginghistory/stage.00003
ln ~/data/staginghistory/stage.00004//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00003/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
ln ~/data/staginghistory/stage.00004//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20150101-20341231.nc ~/data/staginghistory/stage.00003/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20150101-20341231.nc
ln ~/data/staginghistory/stage.00004//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20350101-20541231.nc ~/data/staginghistory/stage.00003/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20350101-20541231.nc
ln ~/data/staginghistory/stage.00004//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc ~/data/staginghistory/stage.00003/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc
ln ~/data/staginghistory/stage.00004//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc ~/data/staginghistory/stage.00003/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc
ln ~/data/staginghistory/stage.00004//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc ~/data/staginghistory/stage.00003/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc
ln ~/data/staginghistory/stage.00004//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00003/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00004//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00003/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
ln ~/data/staginghistory/stage.00004//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20950101-21001231.nc ~/data/staginghistory/stage.00003/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20950101-21001231.nc
ln ~/data/staginghistory/stage.00004//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc ~/data/staginghistory/stage.00003/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc
ln ~/data/staginghistory/stage.00004//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc ~/data/staginghistory/stage.00003/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc
ln ~/data/staginghistory/stage.00004//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20550101-20741231.nc ~/data/staginghistory/stage.00003/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20550101-20741231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/swirrl_fileinfo.json ~/data/staginghistory/stage.00003/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00004//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20750101-20941231.nc ~/data/staginghistory/stage.00003/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20750101-20941231.nc
ln ~/data/staginghistory/stage.00004//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc ~/data/staginghistory/stage.00003/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc
mkdir -p ~/data/staginghistory/stage.00002
ln ~/data/staginghistory/stage.00003//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00002/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
ln ~/data/staginghistory/stage.00003//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20150101-20341231.nc ~/data/staginghistory/stage.00002/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20150101-20341231.nc
ln ~/data/staginghistory/stage.00003//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20350101-20541231.nc ~/data/staginghistory/stage.00002/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20350101-20541231.nc
ln ~/data/staginghistory/stage.00003//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc ~/data/staginghistory/stage.00002/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc
ln ~/data/staginghistory/stage.00003//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc ~/data/staginghistory/stage.00002/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc
ln ~/data/staginghistory/stage.00003//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc ~/data/staginghistory/stage.00002/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc
ln ~/data/staginghistory/stage.00003//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00002/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00003//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00002/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
ln ~/data/staginghistory/stage.00003//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20950101-21001231.nc ~/data/staginghistory/stage.00002/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20950101-21001231.nc
ln ~/data/staginghistory/stage.00003//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc ~/data/staginghistory/stage.00002/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc
ln ~/data/staginghistory/stage.00003//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc ~/data/staginghistory/stage.00002/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc
ln ~/data/staginghistory/stage.00003//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20550101-20741231.nc ~/data/staginghistory/stage.00002/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20550101-20741231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00002/swirrl_fileinfo.json ~/data/staginghistory/stage.00002/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00003//tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20750101-20941231.nc ~/data/staginghistory/stage.00002/tasmax_day_GFDL-CM4_ssp585_r1i1p1f1_gr2_20750101-20941231.nc
ln ~/data/staginghistory/stage.00003//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc ~/data/staginghistory/stage.00002/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc
mkdir -p ~/data/staginghistory/stage.00001
ln ~/data/staginghistory/stage.00002//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00001/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
ln ~/data/staginghistory/stage.00002//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc ~/data/staginghistory/stage.00001/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc
ln ~/data/staginghistory/stage.00002//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc ~/data/staginghistory/stage.00001/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc
ln ~/data/staginghistory/stage.00002//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc ~/data/staginghistory/stage.00001/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20230101-20231231.nc
ln ~/data/staginghistory/stage.00002//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00001/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00002//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00001/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
ln ~/data/staginghistory/stage.00002//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc ~/data/staginghistory/stage.00001/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc
ln ~/data/staginghistory/stage.00002//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc ~/data/staginghistory/stage.00001/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/swirrl_fileinfo.json ~/data/staginghistory/stage.00001/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00002//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc ~/data/staginghistory/stage.00001/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc
ln -s ~/data/staginghistory/stage.00010 ~/data/latest
download_working_dir_data ${NOTEBOOK_URL}/api/contents
delete_notebook http://swirrl-api/swirrl-api/v1.0/notebook
